# Pre-commit configuration to run Ruff, Black, and mypy on changed files
# Install with: pre-commit install
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        additional_dependencies: [
          "pydantic>=2.5.0",
          "types-requests",
        ]
