kind: llm
name: Argo GPT-4
max_move_retries: 3
num_votes: 1
connector:
  model: gpt4
  temperature: 0.2
  max_tokens: null
  timeout: 300.0
  max_retries: 8
  provider: argo
  api_base: https://apps-dev.inside.anl.gov/argoapi/api/v1/resource
handler:
  kind: game_arena
